apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: kubectl
    kubernetes.io/metadata.name: pai
    pai.io/system: 'true'
  name: pai
spec:
  finalizers:
  - kubernetes
