apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pai-aws-credentials
  namespace: pai
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBzSTikYaWzRyc3RwJczmvHOS0EMhRbBzliRkLXYUuw64g2DfnQRveULK4JhfSrpFhRUVkT8QIMqHSro8brixqOsBH8a491TE8NNKePY3s2H3U568+bURFRAXoA35r/D5BkKTcMBbtNBRVnYmtzXpyT/VjOR/vYmnkJXR3BfIjLIBU601XqZV8/hZzatYEspTs27O4jHAdOU2vhU7P/LYb4zOxCwe6O5jvHC9FIIcDyzdWj6Jz0xOACLyE1UKjktQIAhNeVQyp58wiD+Mk5tM/weUTkDGGgFzI++FBWSTnmmZktJkaeRh177VfeHO/IK5zmqVZ90VAw6d2yEBXgk3zBVyAv9O2NpEHO9KzOEz1OC4MzCw+KnAGr8Y0y/WoCNSf6oCADnEWdKQgE4U9R43p8gCkeDx6bXJBemfhlN8c+4WjBX6f/ZNBc+9PO1z55nu4y3cn6In1OCPtxxhjpFJ92lmjncu+l62lsQUV0bNh4c6X7jMX7jhkQVGMBZa/nG2Fp38GaBTqlxATn9isXqrwCE6Vk+HQHkkt9RIJG/UUB59yy316z88Y6pOv9c/1iKebwbl1bDH6Y3nfUPS+vb+SiqNzsDvUz/gx6gSLTmDU8g5s2KCf7rbKufbe7i5lr8Cng+N86aZm4A7C2NDHNboJQhY7vjyMud3KpcAfjbYS0WfPax62TDwzvAS4yNcj3mIhnYVjpwpShUWAf6y2VsyXg4iLe1w==
    AWS_DEFAULT_REGION: AgCqkw1507MD46QasC2lt7KKS4unUvN+tyL8ABKP4NtrL0j/2uHiyVnOjQpy17br2rb4gml9KvI3aQ9iv/Geabbs83QHI+G302335cY6VBC10IuDeMPLwz+WqZ2gGqOUXGxQ6mP4uqSXDJvjS3CDKhR24JxeEanXEbXKbK31cSjAI6UsaS9O/r7nJud35UpHhPPPFNcE0nfGB5CmxWVrpbKaPKh70lkoaFzltgjfBooA5mSpwuZz9bOGSyvXXqmv/005AAIUJToqk0x7mcAvafrsy+AiLGea+dDABGpl6T3WsCiSRoRnZ/wlyDeUgUv5+T5sJ/9gUdVBv2DHPlxAspbTRD6I2mFcTc+EoVA8kzHSeNbFaAGMdNPKYBWU0Mdppoj/P4meVsQr0BpBIcPhBYoA4bTCf0IbC+u8WaVcErTeq3GeTfRFxggRmo4trX9eti3UjZ7wqkNkeVEfJunvIlFuK5/NrhC+5pHPIT8Y1lKTDLooQjPLgfYxmZbauobrX2kxpU2yGZWYC4A7ykltrwWh19snT10GSc6nDQ35vMC5Q5VjGDZ/UQyZovzAgcKO51PxAbZLxf6mHe7bzbL7fjSeDqp1fqRhLH79QudHdFfniae7E0vX8p1Nlqt5ALytx7xlHspJ5ag4qeYpZjov/J9FSPIW0Mj5ZbVyffXX2hAk2FSoSDn5PpPcjeU7W8/aFJeHvQFpZVyS6fQ=
    AWS_SECRET_ACCESS_KEY: AgCBvfOm38oirahQsXUbZVqxjmAUmKTKP7zFjzJN8r6zzvKLLMQDvqpv2djlg1LuH1KAAMT4q7o0x3W+FgAjGDxno9JbdQFh6uXzeOQy1y+LGTcOQbG4Fn/Q3QcSY/y+AoPtVoOyOZkzUzbYELCLTE2q7t+NGmGWPrshK89YwoiOkPMcdavvjVppYWKZqcY24LRzXgtcjbwJ8u5Qh6h0SYTejy4w1TSOSYoNRexcP+lZE67pDMq4GeWESkDYsgTVYGRwiVXjRjjmE31rn10M27+hu6iywfaD7CIlpY0hxcC9mmsSSQ1ONy8cLCtptOTexe/ruFXQiq/WvMXD9LGgNz/9IRG1p1PgsIYmRVLEozc6E4cNBjy4vNGEKOfjg6x70SDTq7sRo06/QPxxgRY/J0yd/AHnUhQ3FqqKD78wCNaFyZ1Z2u/iEixT3RVf4J8ImTPy5Q/yJOYySU5PGs5ZkqivjnrzknddGHurCsUUoBvUVLFzLn6p5ZIF4+4EBtiMR2V0/GblAzjSt9VeQPs0cUvjiWFJEhSQYkA7fswKt1VyY7nn67XTccARxmod4z/xDG0W1zwWQjuvt2AULOpzjL2acA1lR0+T/AXuISazwJjwgOixPcomNWwAOQsAxDAdOrziThw4qyRTwgb2mQp5hK/aJ/vM8T0kq+Mx+eX9HeKmHYjellhPIH7v46CULPV3mNBCKjHc1k1ICDt0PwxRPErfJHNoOnGtKRruuhWaKVJyl0Yt/jgOGNPo
  template:
    metadata:
      name: pai-aws-credentials
      namespace: pai
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pai-claude-api-key
  namespace: pai
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgC8eBVVIT8bbvQ8cmybB6wii1+W1TwyhhzOpwX7VeezZ3ynj/U7ruxWbdleKQ3q3SHfEsVADbym1iD6DmvSOM0LAcAfg5EwJgMdQ5abPM3G9uxaiAGvUNbr+KFZ1LnekjLgTUB/unWYITUXeAnXsrJ2lkXLkasSsOZCUIEMe6DoXfKM5aLIqyd2KayFYtd9K+hSd6VM7O8NSOx2mRqZsmp+x+LrRzbPDhJIJQ67I+Csh0JWyiy9i0TNLBP9LDIZNkL5H42OzebzDy5WU/11HeG/56KJw340Mat+JZtWdYAqD/QrGxVJhDuw98YTXfl+FaWl5wf6T33X5ozlTh9xUtdi6Os2zKLgz/mHU+lj9/te4F2Wa/EdAzbJ85yT3FzFGs+uySH8K0RmHPFfaIqADYu5PPxwn1dWmiuZ1yNxG4X5R28H1I1HYVK5ERx0AqQwHcLLeIIg+dJ7MAbKGFGtOU2UOm83NNlT2r+CKEeju2d7YlrlQBgghmNJte56xc8OTrf+t0hTd1SMA9mNfzkWHXERtQrR/gtuLjmu8KBQYwSBGa3BVNcyCTRrxxtEEsCaqKH00hK7o6ygl/eoHORMVvo+hTFhNd1WyLR/qJEXeHTDVr/78xhHtqOzaI6YRyysAKFqrG4FleeyikRW0XD5bxPPgxPq2Qn+1cZPBZbs2Qg8S4+/3mi8BQtgA+Z4FfQ3FDg=
  template:
    metadata:
      name: pai-claude-api-key
      namespace: pai
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pai-resend-api-key
  namespace: pai
spec:
  encryptedData:
    RESEND_API_KEY: AgA00TdCtGDFMWaX70JqEnpwn/nrJxB/8kB6uEa+LwKX3Hy0Gc2OBKdcNgWO+H2Q53JXGknulr4mijqMQNoRJSxAGppUl1Gg8opA/VmIRagl3FAvn2fDUEP9uZUb9iHRXDmesU9EjYdxAHyfJTZk42AeLLt5s+XwDRODobpTAFEcL2V76ZaFNXOFhy+9OpR8bEjWOqn+xZh0VNYfFpNpcSZ4pwx9+NRB+hnRdTit4OR9WD+Fm1GM0IkS8ZO0QCT1QTOvRofqRmHl72AFmUlTFFoFjo4NJAdrOPRG+RwbX+YVJ5zd4BrE+s1rnA9IokDR7L/0UnvxKIiXf+LJSgndGF6XbfRmv/erFNKaLO9i/YckMwSRTbXdFYtyjuonjpASQF4sEFmBOGb9vMAVq6MDyhT3txXEFLenULzJOTjPWe/BcAzAvI9Had1qp2NHssovD8gbuXSSKhoJoV8q1/DR4d4HC+b10MwRWRK5PvTv9TsRmcdzpkx8OiOTfkxK5Fa/drY95EEBAFZqsVParAWjYv1IwGi/NT4oZsZ583E1aGfIFqyCOg/KFuKSXLWIE0LKvIIMpXflAmY22k92FtWV7eDhGgqS49m9BZhbrpYIjz3DROq4s2vnY3BvgEAyLrsV8Y2qqHNL2U/tpLdO9h8F0qt86jEdgpK/c5jkynYVxa/8ZoLafmB4hQVWsQwSzP1ZV90=
  template:
    metadata:
      name: pai-resend-api-key
      namespace: pai

