---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: woodpecker-agent-1-secret
  namespace: woodpecker
spec:
  encryptedData:
    WOODPECKER_AGENT_SECRET: AgCUOZmSLS1hwh14zskwxQTJkgreuA+QGoqVIO0JXPZnWrv+gDNUV/GS6PTxHJOHJYGMZKMy5ToAZwAiD/+yXhuHFsnO8KsLJQD9MN8rvRFWYPVInKIzSMZ0skt3EsNAK4C6uohgWg1X6CpChuoOnciANwBbLUvlpA3IL0zlbe0VY4gQJrFowaeosMDP4ahLMnZKjTFmz9i7t8FFd4Xiyh0AjAQxvEuQKvoY830YWQjzqqd2EGSGAq+pUD5tUgVwFSCMZLet4BBgppiNZC7l0oybjdG6uRjGUM3eRdRkpLCyCv6wL2SfkqLcwD0nI/qZyuyAEYsTn2y+HZwnxBQdsTEw+jGVhtp6G/w4xFiYGOQWDDxoTN8azhiIELy2ICQK4W5JfPG3DuhAY2d67ZXYZ06OBWgb24QDxT2DFahF4VRl18Pa4VMvrbDSeXrUbRMM1akE8T7IbZ7Es1HOLQxvVBdL+//R7I41Di1myZHK/+SKWGCaqnZi7SnniEFQ2AnH1/WyGHbQ4u6hGqJRhgv+hdveMqqmEEisNLlYWEf5LcYU5sb27ULk5/7HtNVbwmRbmQrDInPyBQ2tnmy9lYCKGUH8BlcZQ9tx/5ps/TmEQVKrjnRenKoajHotXuuTDoOnf0AkF3gSNr7VMR0629bl5rAKx8xnaHPG0SjsReoU6EjjquOQi/zND3AvkdB9VO7CRe5bHrTakZWzLoW5T/caD8806B56XOMQvtt4GDAfTCz3a2QVwCKeKvMXA/mrHV8WURePOM62ReFc4w==
  template:
    metadata:
      creationTimestamp: null
      name: woodpecker-agent-1-secret
      namespace: woodpecker
