---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgAXN11SLZGlEnPJuX8bKO7c0+lj+VsQ7CnEfLqwa2JUNPeX0cO9TrXCkqAxOYF0ER8gyPERrqDONM6wShWwnFSrgasltLHZdaRwqv8+mt4laTdq/p7ebIc+kGarScnNeBjt12HFe2UynvecQpAw1mv9FDJCLrD0/llTo7quj7ERD8MyakghcGLmR1CfI+8jkLljT29g9MRmHN4+HIbsZIvFu/KiYioOdDWaDZJDx81yDEBeUNECThXelsOVUbMAliMw6s9uQ6HTkxBdl1B5zrpLcAWx8tvv38ritE3QKwYT3QYy4FUOE+IM8HcebDSQqxGuzJVmN2IDhxsg7cy8cEfIMjiZGBEnbVIJ8o9wmR25G0peRFMb3K7moD14GZICxRwgw+kANPsHH3K/nwovo2YD5EAWnhXyg7rxQEEWZ5HkARa5OvEjuh+HgYHuLFidpbeXGqT2m9IHnXTvt8/PXMMduR17RPLmw64lOnLIQhRSGNFgWz5keZqbCcQCD71dSiG0Igg1qPJ39eEXOJCyPx/WSLx8PktdffO8t19I7rEYnddTEs7xU4miiRAL1oinkm5RO2VmLZMIeCeqjWJNMmbUhJM0v20uuntJVH2A54vQG/UIELe67Uw+uevokj49jUMJ2j6Nl9AyMEx3AAr4Em2YUzVv+f2wYlam2GcA6lpHUCRPo2C74C9FzRqA2fYTQLJng2ZfZy0/guGxp9JCiKwPOG0ht3qVt9TJry41ca+ox5K1W9cTLoNBBbZaUu9r4zPqW3M7ybCLWsaQrL5ivKR3QQUEF8moasZvzF79EEFXq+Yb6K3sMX0k4XFFOGzHnxGaCnNeXGnfCfGeLECeK2SgNWEvP+HFKxEKGkIpM8nHky3dEHL69JVCedF3yr93PmK/GBUfyBnA+c9N6uhCPa06v14sLbDoKzIqx6yLAuIn3UvnINc9jdWtEqeytlyJDJeIQk7HWWCExewpPOnXvg8S/YSmVYJHOMtdZIL+mFzZ535YjjtDAhV+LJUj8clLAXs=
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflare
    type: Opaque
